### ISSUE TITLE
how to auto enable this script when mpv launched?

### ISSUE THREAD

**Issue by rsyqvthv** [mesvam/ff-silence#2]
Thanks.

**Comment by mesvam** [comment]
--script-opts-append=ff_silence-enabled=true

**Comment by rsyqvthv** [comment]
I would like to use mpv.conf, tried to "add script-opts-append=ff_silence-enabled=true to mpv.conf", but seems it don't work. 

I open mpv after alter the mpv.conf, drag a mp4 clip on it, silence isn't skipped. I have to use shortcut to enable it, then silence is skipped.

any idea?

**Comment by mesvam** [comment]
Hmm... not sure. I have `script-opts-append=ff_silence-enabled=true` in `mpv.conf` and it works on my end. Does it work on a new profile?

Otherwise, the only thing I can think of right now is that it waits for a `file-loaded` event before enabling, so if something doesn't load properly, it might wait forever.

**Comment by rsyqvthv** [comment]
thanks for your reply, followed your hint to make a new profile found it works. so I thought it must conflict with settings in mpv.conf

as I troubleshooting line by line, find I use "script-opts" for another script, which is overwrite ff-silence's "script-opts-append", when I changed that to "...-append", issue has gone. 

Thanks for your help. :)
